### ISSUE TITLE
Enhancement: Modify `TestSuite` and `TestFile` classes for better source handling

### ISSUE THREAD

**Issue by ThePinion** [visoftsolutions/cairo-webauthn#1]
The current implementation of our `TestFile` and `TestSuite` classes requires certain improvements in terms of the way we handle and refer to the source files. This issue details the proposed improvements for this implementation.
**Current Implementation** (```session-token``` branch):
```python
class TestFile:
    # ...

    def __init__(self, name: str, python_source: str) -> None:
        # ...

class TestSuite:
    # ... 

    def __init__(self, path: str, mod_file_path: str) -> None:
        # ...
```

**Proposed Changes**:

1. **TestSuite Class Modification**:
    - Add a new field called `python_source_folder` to the `TestSuite` class.
      This field will store the folder in which the python scripts generating the tests are.

2. **TestFile Class Modification**:
    - Instead of passing the `python_source` to the `TestFile` constructor, we should pass `python_suite_source`.
    - Modify the __init__ method to appropriately construct the self.python_source value. The intended result should combine python_suite_source, the given name, and the '_test.py' suffix or similar.

3. **Update Occurrences**:
    - Update all occurrences in the codebase where the constructors for `TestSuite` and `TestFile` are being used to reflect the above changes.
    
**Optional Improvement**:

In the current setup, when constructing a test suite, we have a repetitive pattern:
```python
suite = TestSuite("src/auth/src/tests", "src/auth/src/tests.cairo")
```
After the proposed changes, it further extends to:
```python
suite = TestSuite("src/auth/src/tests", "src/auth/src/tests.cairo", "test_gen_scripts/auth")
```

To enhance clarity and reduce repetition, it might be beneficial to provide only the base path of the suite, the name of the suite, and the script directory as arguments. The remaining parts of the paths can then be programmatically constructed based on these inputs.

For example, we could consider a design where the constructor takes in the path of the suite `"src"`, the name of the suite `"auth"`, and the script directory `"test_gen_scripts"`, and then internally constructs the necessary paths using these parameters. This would simplify instantiation and reduce the possibility of errors.

---

**Verification**:
After the changes are done, verify that the scripts are generated correctly by running:
```python
python test_gen_scripts/main.py
```
Ensure that the comments in the generated files are generated correctly. For instance, in `src/auth/src/tests/expand_auth_data_gen_test.cairo`, the current comment block is:
```
// This file is script-generated.
// Don't modify it manually!
// See test_gen_scripts/expand_auth_data_test.py for details
```
After the changes, it should be:
```
// This file is script-generated.
// Don't modify it manually!
// See test_gen_scripts/auth/expand_auth_data_test.py for details
```

---

**Tasks**:

- [ ] Add `python_source_folder` to the `TestSuite` class.
- [ ] Modify the constructor of `TestFile` to use `python_suite_source`.
- [ ] Update all occurrences of `TestSuite` and `TestFile` constructor usage.
